### ISSUE TITLE
Colorpicker doesn't show up correctly when using a variable as a placeholder

### ISSUE THREAD

**Issue by kinging123** [ruhley/angular-color-picker#122] opened 2016-10-25 16:21 UTC
Here's a Plunkr demo:
https://plnkr.co/edit/Ho9NBEogYkqrU0w6UpnV?p=preview

The placeholder shows just fine but everything else is messed up.

This code works:

``` html
    <color-picker ng-model="primary_color" options="{placeholder: '#123456'}" ></color-picker>
```

This doesn't:

``` html
    <color-picker ng-model="primary_color1" options="{placeholder: myColor}" ></color-picker>
```

(When $scope.myColor is defined)

**Comment by nati-mask** [comment] 2016-10-25 16:47
Your Plunkr shows me good results, the *placeholders* are as intended...

**Comment by kinging123** [comment] 2016-10-25 16:53
Forgive me if I haven't described the issue correctly.

The *placeholders* are working just fine, but try to click on the colorpicker:

The second one works fine:
![image](https://cloud.githubusercontent.com/assets/5137073/19695646/aaf98282-9aec-11e6-99a5-32d34bd0fc96.png)

The first one though shows only red colorpicker and no bootstrap addon:
![image](https://cloud.githubusercontent.com/assets/5137073/19695664/b8c76bf4-9aec-11e6-830a-9d7f54780588.png)

**Comment by ruhley** [comment] 2016-10-25 23:02
In your scenario on this line (https://github.com/ruhley/angular-color-picker/blob/master/src/scripts/controller.js#L402) it tries to merge the passed in options object with the default options object. Logging out the options object after the merge function results in the expected output. However outputting the options object in the html `{{AngularColorPickerController.options}}` only shows the provided options object, not the merged one. This only happens when using and inline options object - 

```html
<color-picker ng-model="color" options="{placeholder: myColor}" ></color-picker>
```

This does not happen if the options object is a defined variable and still using a variable in the placeholder.

```js
$scope.options = {
    placeholder: myColor
};
```
```html
<color-picker ng-model="color" options="options" ></color-picker>
```

It also works as expected if after the merge I assign the options object to another variable `this.optionsClone = this.options;` and then use that. I feel like this is some sort of weird AngularJS bug that two way binding doesn't work on inline objects with a variable. 

If you absolutely have to pass in the options object inline then I put in the `optionsClone` hack for you. However I would rather fix the root cause of the problem.

**Comment by ruhley** [comment] 2016-11-08 05:23
I am closing this issue as there has not been an update in a while and I believe it is an AngularJS bug. Please reopen this issue if you feel it has not been resolved.

**Closed by ruhley** 2016-11-08 05:23 UTC
Labels: bug
