### ISSUE TITLE
ng-repeat and api attribute

### ISSUE THREAD

**Issue by Lukinos** [ruhley/angular-color-picker#85] opened 2016-07-11 14:01 UTC
Hi,
I have a bug with the color-picker 2.0.0. It happens when you do a `ng-repeat ` to generate a list of color-picker, but only when you use the attribute `api`.

Concretely, when you try to change the color of the first color-picker (or any other) of the list, it will modify instead the last color-picker.
The bug does not appear if I do not use the `api` attribute.

Here a [JSFiddle](https://jsfiddle.net/t4q4nrfp/60/) that will be, I hope, more clear than my explanation.

**Comment by ruhley** [comment] 2016-07-11 22:35
I have updated the [JSFiddle](https://jsfiddle.net/wnhqos24/1/) with a working version. You need to create a separate api object for each color picker. 

What are your thoughts on the expected behaviour? What do other libraries do?

**Comment by tristar500** [comment] 2016-07-12 02:00
I made a new version of that fiddle https://jsfiddle.net/5wn5dhw5/9/

This doesn't seem to be consistently firing the events.

**Comment by ruhley** [comment] 2016-07-12 02:46
You need to create a separate api for each color picker. See my updated fiddle - https://jsfiddle.net/fm2Lvbe9/.

**Comment by tristar500** [comment] 2016-07-12 03:48
So how would one do this when the length of the color list is dynamic? Don't always know how many items will be in the list.

**Comment by Lukinos** [comment] 2016-07-12 07:36
As I wanted to have a generic behaviour across all my color-pickers that's why I expected to use only one api object; I have not thought about having an api object for each color-picker.

For instance, [ui-boostrap](https://angular-ui.github.io/bootstrap/#/alert) uses only one `onClose` function for all the alerts in their example.

**Comment by Tim-Intellipharm** [comment] 2016-07-12 08:00
The reason for the separate apis is that you can also programmatically control some things of the color picker (e.g. show or hide), so I can only think of two ways to suit all scenarios:

- Only have one api for all color pickers, but require a color picker object for actions (i.e. show or hide) so it knows which color picker to do the action against.
- Seperate the concerns by creating a new `eventApi` that handles all the events like `onChange` or `onClose`. Then you could have the one `eventApi` for all the color pickers but it would still need separate `api` for each color picker.

What are your thoughts?

**Comment by ruhley** [comment] 2016-07-12 08:01
The reason for the separate apis is that you can also programmatically control some things of the color picker (e.g. show or hide), so I can only think of two ways to suit all scenarios:

  * Only have one api for all color pickers, but require a color picker object for actions (i.e. show or hide) so it knows which color picker to do the action against.
  * Seperate the concerns by creating a new eventApi that handles all the events like onChange or onClose. Then you could have the one eventApi for all the color pickers but it would still need separate api for each color picker.

What are your thoughts?

**Comment by Lukinos** [comment] 2016-07-12 08:43
Ok, I understand your point.
I would choose the second one. Having a eventApi for the `onXXX` and another specific actionApi for the open/close.

The first proposition seems a little confusing to me.

**Comment by tristar500** [comment] 2016-07-12 13:37
I think the second choice as well. In my particular scenario, I just need to know when a color picker has changed, I don't care which one, because the architecture of this app just saves all of them at the same time.

Also, if we can pass in the row object, then we can figure out which item id we're working with and handle it in all encompassing onChange handler.

**Comment by ruhley** [comment] 2016-07-12 22:47
Fixed in commit 341d727dd24634d75bfe130872a7428ef9b0459a and released in [v2.1.0](https://github.com/ruhley/angular-color-picker/releases/tag/v2.1.0)

**Closed by ruhley** 2016-07-12 22:47 UTC
Labels: bug
